import Foundation

/// Noise QR link generated by this fork's `openflux --share`.
struct ShareLink: Decodable {
    let transport: String
    let url: String
    let peerKey: String

    static func decode(_ link: URL) -> ShareLink? {
        guard link.scheme == "openflux", link.host == "noise-v1" else { return nil }
        let encoded = String(link.path.dropFirst())
        guard !encoded.isEmpty, encoded.count <= 4096 else { return nil }
        let standard = encoded.replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        let padded = standard + String(repeating: "=", count: (4 - standard.count % 4) % 4)
        guard let data = Data(base64Encoded: padded),
              let value = try? JSONDecoder().decode(ShareLink.self, from: data),
              ["yandex", "vyandex", "cupsonline", "mailru"].contains(value.transport),
              !value.url.isEmpty, value.url != "http://#", value.url.count <= 2048,
              value.url == value.url.trimmingCharacters(in: .whitespacesAndNewlines),
              let key = Data(base64Encoded: value.peerKey), key.count == 32 else { return nil }
        return value
    }
}
